## 카드 제목 및 링크 크롤링

In [175]:
# pandas : 파이썬에서 사용할 수 있는 엑셀과 유사한 데이터분석 도구
# numpy : 파이썬에서 사용할 수 있는 공학용 계산기
# requests : 매우 작은 브라우저로 웹사이트의 내용과 정보를 불러옴
# BeautifulSoup : requests로 가져온 웹사이트의 html 태그를 찾기위해 사용
# time : 간격을 두고 가져오기 위해 사용

import pandas as pd 
import numpy as np 
import requests 
from bs4 import BeautifulSoup as bs
import time
import json

In [177]:
url = 'https://www.shinhancard.com/logic/json/cardinfo_data.json?v=1682753768670'

In [180]:
card = requests.get(url)
card_data = card.json()

In [181]:
# card_url key : 'hpgCrdPdUrlAr'
# card_name key : 'hpgCrdPdNm'

card_list = [{'card_name' : 'card_name', 'card_url' : 'card_url'}]

for card in card_data['cardInfo']:
    if 'hpgCrdPdUrlAr' in card:
        card_list.append(
            {
            'card_name' : card['hpgCrdPdNm'],
            'card_url' : card['hpgCrdPdUrlAr'],
            }
        )

In [182]:
card_name = []
card_url = []

for i in card_list :
    card_name.append(i['card_name'])
    card_url.append(i['card_url'])

In [183]:
card_data = pd.DataFrame()

In [184]:
card_data['카드이름'] = card_name
card_data['카드 URL'] = card_url
card_data = card_data[1:]

In [185]:
card_data['카드 URL']

1      /pconts/html/card/apply/prepaid/1221697_2387.html
2      /pconts/html/card/apply/prepaid/1221540_2387.html
3      /pconts/html/card/apply/prepaid/1221539_2387.html
4        /pconts/html/card/apply/check/1221538_2206.html
5        /pconts/html/card/apply/check/1221536_2206.html
                             ...
660     /pconts/html/card/apply/credit/1195371_2207.html
661      /pconts/html/card/apply/check/1195342_2206.html
662      /pconts/html/card/apply/check/1195343_2206.html
663      /pconts/html/card/apply/check/1195344_2206.html
664     /pconts/html/card/apply/credit/1195357_2207.html
Name: 카드 URL, Length: 664, dtype: object

In [186]:
card_data.loc[:,'카드 URL'] = 'https://www.shinhancard.com' + card_data['카드 URL']

In [187]:
card_data

,카드이름,카드 URL
1,부산동고등학교 신한 Meme(밈) 학생증 카드,https://www.shinhancard.com/pconts/html/card/a...
2,신한카드 Pick I 선불,https://www.shinhancard.com/pconts/html/card/a...
3,신한카드 Pick E 선불,https://www.shinhancard.com/pconts/html/card/a...
4,신한카드 Pick I 체크,https://www.shinhancard.com/pconts/html/card/a...
5,신한카드 Pick E 체크,https://www.shinhancard.com/pconts/html/card/a...
...,...,...
660,한국전력공사 복지 신한카드 Love,https://www.shinhancard.com/pconts/html/card/a...
661,신한카드 JYP Fan’s EDM 트와이스 체크,https://www.shinhancard.com/pconts/html/card/a...
662,신한카드 JYP Fan’s EDM 갓세븐 체크,https://www.shinhancard.com/pconts/html/card/a...
663,신한카드 JYP Fan’s EDM 데이식스 체크,https://www.shinhancard.com/pconts/html/card/a...
664,파인애플 신한카드,https://www.shinhancard.com/pconts/html/card/a...

## 각 홈페이지 별 혜택 크롤링

In [263]:
# 헤택 정보 저장 
bonus_list = []

for url in card_data['카드 URL'] :

    headers ={"user-agent":"Mozilla/5.0"}
    html = requests.get(url, headers = headers)

    ## 한글 깨짐 현상 해결 :  utf-8로 바꾸어 주기
    html = html.content.decode('utf-8','replace')
    soup = bs(html, 'html.parser')
    
    # 연회비 삭제 
    temp = soup.find_all('strong')[1:]
    
    empty = []
    for i, j in enumerate(temp):
        empty.append(str(i+1) + '. ' + j.text)
    bonus_list.append(" ".join(empty))

In [265]:
card_data['혜택'] = bonus_list

In [266]:
card_data

,카드이름,카드 URL,혜택
1,부산동고등학교 신한 Meme(밈) 학생증 카드,https://www.shinhancard.com/pconts/html/card/a...,1. 특별적립 2. 기본적립 3. 교통기능 4. 금융기능 5. 공통유의사항 6. 특...
2,신한카드 Pick I 선불,https://www.shinhancard.com/pconts/html/card/a...,
3,신한카드 Pick E 선불,https://www.shinhancard.com/pconts/html/card/a...,
4,신한카드 Pick I 체크,https://www.shinhancard.com/pconts/html/card/a...,
5,신한카드 Pick E 체크,https://www.shinhancard.com/pconts/html/card/a...,
...,...,...,...
660,한국전력공사 복지 신한카드 Love,https://www.shinhancard.com/pconts/html/card/a...,1. 쇼핑 할인 2. 쇼핑 무이자 할부 3. 주유 할인 4. 요식/커피 할인 5. ...
661,신한카드 JYP Fan’s EDM 트와이스 체크,https://www.shinhancard.com/pconts/html/card/a...,1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
662,신한카드 JYP Fan’s EDM 갓세븐 체크,https://www.shinhancard.com/pconts/html/card/a...,1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
663,신한카드 JYP Fan’s EDM 데이식스 체크,https://www.shinhancard.com/pconts/html/card/a...,1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
664,파인애플 신한카드,https://www.shinhancard.com/pconts/html/card/a...,1. SKT 라이트할부 2. 통신요금 할인 3. 주유 적립 4. 영화 할인 5. 테...

In [288]:
card_data['혜택'] = card_data['혜택'].astype('string')

In [290]:
card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 1 to 664
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   카드이름    664 non-null    object
 1   카드 URL  664 non-null    object
 2   혜택      664 non-null    string
dtypes: object(2), string(1)
memory usage: 15.7+ KB

In [292]:
card_data['혜택']

1      1. 특별적립 2. 기본적립 3. 교통기능 4. 금융기능 5. 공통유의사항 6. 특...
2
3
4
5
                             ...
660    1. 쇼핑 할인 2. 쇼핑 무이자 할부 3. 주유 할인 4. 요식/커피 할인 5. ...
661    1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
662    1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
663    1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
664    1. SKT 라이트할부 2. 통신요금 할인 3. 주유 적립 4. 영화 할인 5. 테...
Name: 혜택, Length: 664, dtype: string

In [293]:
# 공백 문자란 nan 으로 변환 
['혜택'].replace('', np.nan, inplace=True)

In [295]:
# 결측치 확인 후 제거 
card_data['']

      카드이름  카드 URL     혜택
1    False   False  False
2    False   False   True
3    False   False   True
4    False   False   True
5    False   False   True
..     ...     ...    ...
660  False   False  False
661  False   False  False
662  False   False  False
663  False   False  False
664  False   False  False

[664 rows x 3 columns]

In [299]:
# 결측치 제거
card_data = card_data.dropna()
card_data

,카드이름,카드 URL,혜택
1,부산동고등학교 신한 Meme(밈) 학생증 카드,https://www.shinhancard.com/pconts/html/card/a...,1. 특별적립 2. 기본적립 3. 교통기능 4. 금융기능 5. 공통유의사항 6. 특...
8,부산동고등학교 신한카드 틴즈플러스 포니 체크,https://www.shinhancard.com/pconts/html/card/a...,1. 영화 할인 2. 테마파크 할인 3. 영푸드 캐시백 4. 서비스 상세기준 5. ...
9,양영디지털고등학교 신한 Meme(밈) 학생증 카드,https://www.shinhancard.com/pconts/html/card/a...,1. 특별적립 2. 기본적립 3. 교통기능 4. 금융기능 5. 공통유의사항 6. 특...
10,태백기계공업고등학교 신한 Meme(밈) 학생증 카드,https://www.shinhancard.com/pconts/html/card/a...,1. 특별적립 2. 기본적립 3. 교통기능 4. 금융기능 5. 공통유의사항 6. 특...
11,경남자동차고등학교 신한 Meme(밈) 학생증 카드,https://www.shinhancard.com/pconts/html/card/a...,1. 특별적립 2. 기본적립 3. 교통기능 4. 금융기능 5. 공통유의사항 6. 특...
...,...,...,...
660,한국전력공사 복지 신한카드 Love,https://www.shinhancard.com/pconts/html/card/a...,1. 쇼핑 할인 2. 쇼핑 무이자 할부 3. 주유 할인 4. 요식/커피 할인 5. ...
661,신한카드 JYP Fan’s EDM 트와이스 체크,https://www.shinhancard.com/pconts/html/card/a...,1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
662,신한카드 JYP Fan’s EDM 갓세븐 체크,https://www.shinhancard.com/pconts/html/card/a...,1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
663,신한카드 JYP Fan’s EDM 데이식스 체크,https://www.shinhancard.com/pconts/html/card/a...,1. Brand Story 2. 콘서트 예매 캐시백 3. 음원/스트리밍 캐시백 4....
664,파인애플 신한카드,https://www.shinhancard.com/pconts/html/card/a...,1. SKT 라이트할부 2. 통신요금 할인 3. 주유 적립 4. 영화 할인 5. 테...